# Generated by Django 4.2.11 on 2024-03-11 16:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travellerprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveller',
            name='profile_photo',
            field=cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
