# Generated by Django 4.2.11 on 2024-03-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travellerprofile', '0002_alter_traveller_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveller',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='profileImages/'),
        ),
    ]
